version: 0.0
os: linux
files:
  - source: /
    destination: /var/codedeploy/ec-cube
permissions:
  - object: /var/codedeploy/ec-cube
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: ec2-user
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ec2-user
